#ifndef TASK_MANAGER_VERSION_H
#define TASK_MANAGER_VERSION_H

#define TASK_MANAGER_VERSION_MAJOR 1
#define TASK_MANAGER_VERSION_MINOR 12
#define TASK_MANAGER_VERSION_PATCH 4

#define TASK_MANAGER_STRINGIFY_INNER(value) #value
#define TASK_MANAGER_STRINGIFY(value) TASK_MANAGER_STRINGIFY_INNER(value)
#define TASK_MANAGER_VERSION_STRING TASK_MANAGER_STRINGIFY(TASK_MANAGER_VERSION_MAJOR) "." TASK_MANAGER_STRINGIFY(TASK_MANAGER_VERSION_MINOR) "." TASK_MANAGER_STRINGIFY(TASK_MANAGER_VERSION_PATCH)

#endif
